CREATE TABLE IF NOT EXISTS client (
	phone VARCHAR NOT NULL,
	email VARCHAR NOT NULL,
	last_name VARCHAR NOT NULL,
	first_name VARCHAR NOT NULL,
	"password" VARCHAR NOT NULL,
	has_legaGuardian BOOL NOT NULL,
	id int NOT NULL GENERATED BY DEFAULT AS IDENTITY
);

CREATE INDEX client_id_idx ON public.client (id);
CREATE INDEX client_phone_idx ON public.client (phone);
CREATE INDEX client_email_idx ON public.client (email);

